backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: 'public/images/uploads' # Folder where user uploaded files should go
public_folder: '/images/uploads'

slug:
  encoding: "ascii"
  clean_accents: true

collections: # A list of collections the CMS should be able to edit
  - name: 'post' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Blog Post' # Used in the UI, ie.: "New Post"
    folder: 'src/content/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format: 'frontmatter'
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "@layouts/BlogLayout.astro"}
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Date de publication', name: 'created_at', widget: 'datetime', default: "", format: 'YYYY-MM-DDTHH:mm:ss'}
      - { label: 'Vignette', name: 'vignette', choose_url: false, widget: 'image', required: false, optional: true, }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'Jugements' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Jugements ' # Used in the UI, ie.: "New Post"
    folder: 'src/content/jugements' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format: 'frontmatter'
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "@layouts/BlogLayout.astro"}
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Date de publication', name: 'created_at', widget: 'datetime', default: "", format: 'YYYY-MM-DDTHH:mm:ss'}
      - { label: 'Vignette', name: 'vignette', choose_url: false, widget: 'image', required: false, optional: true, }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    folder: 'src/pages'
    create: true
    nested:
      depth: 10 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    format: 'frontmatter'
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "@layouts/BlogLayout.astro"}
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Image de couverture', name: 'vignette', choose_url: false, required: false, optional: true,
       widget: "image"}
      - { label: 'Contenu', name: 'body', widget: 'markdown' }