backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: 'public/images/uploads' # Folder where user uploaded files should go
public_folder: '/images/uploads'

collections: # A list of collections the CMS should be able to edit
  - name: 'post' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Blog Post' # Used in the UI, ie.: "New Post"
    folder: 'src/content/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format: 'frontmatter'
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "$/layouts/BlogLayout.astro"}
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Contenus', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      # - { label: 'Tags', name: 'tags', widget: 'list' }
      # - { label: 'Author', name: 'author', widget: 'string' }
      # - { label: 'Author Twitter Handle', name: 'authorTwitter', widget: 'string' }
      # - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  - name: 'pages'
    label: 'Pages'
    folder: 'src/pages'
    create: true
    format: 'frontmatter'
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "$/layouts/BlogLayout.astro"}
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Contenus', name: 'body', widget: 'markdown' }